name: PHP Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: echohello-dev/actions/php-lint@main
        with:
          who-to-greet: 'Mona the Octocat'